### ISSUE TITLE
MacBookAir9,1 6.6.5-200.t2.fc39.x86_64  and suspend

### ISSUE THREAD

**Issue by 392a5237** [t2linux/fedora#26]
Hi guys. There is a problem. After falling asleep, the keyboard and touchpad do not fully work. Any ideas ?
[AIR.txt](https://github.com/t2linux/fedora/files/13635288/AIR.txt)

**Comment by sharpenedblade** [comment]
Closing, if this still happens make a new issue for the latest kernel.
