### ISSUE TITLE
Grub no longer shows t2 kernels

### ISSUE THREAD

**Issue by MarjaE2** [t2linux/fedora#39]
I've had several updates of the standard Fedora versions of the Linux kernels.

But I haven't had updates of the t2 Fedora versions, and checking the wiki, I can't find an explanation of how to do updates. Now the t2 versions have disappeared from Grub, because there are to many newer non-t2 versions.

**Comment by sharpenedblade** [comment]
It worked fine for me. Run `sudo dnf repolist`, `sudo dnf info kernel-core`, `find /boot/efi`, and `ls /usr/lib/modules`, then post the output.

**Comment by MarjaE2** [comment]
sudo dnf repolist:

repo id                                               repo name
copr:copr.fedorainfracloud.org:phracek:PyCharm        Copr repo for PyCharm owned by phracek
copr:copr.fedorainfracloud.org:sharpenedblade:t2linux Copr repo for t2linux owned by sharpenedblade
fedora                                                Fedora 40 - x86_64
fedora-cisco-openh264                                 Fedora 40 openh264 (From Cisco) - x86_64
google-chrome                                         google-chrome
rpmfusion-nonfree-nvidia-driver                       RPM Fusion for Fedora 40 - Nonfree - NVIDIA Driver
rpmfusion-nonfree-steam                               RPM Fusion for Fedora 40 - Nonfree - Steam
updates                                               Fedora 40 - x86_64 - Updates

**Comment by MarjaE2** [comment]
sudo dnf info kernel-core:

Last metadata expiration check: 0:51:29 ago on Fri 05 Jul 2024 08:42:21 PM EDT.
Installed Packages
Name         : kernel-core
Version      : 6.9.5
Release      : 200.fc40
Architecture : x86_64
Size         : 69 M
Source       : kernel-6.9.5-200.fc40.src.rpm
Repository   : @System
From repo    : updates
Summary      : The Linux kernel
URL          : https://www.kernel.org/
License      : ((GPL-2.0-only WITH Linux-syscall-note) OR BSD-2-Clause) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR BSD-3-Clause) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR CDDL-1.0) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR Linux-OpenIB) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR MIT) AND
             : ((GPL-2.0-or-later WITH Linux-syscall-note) OR BSD-3-Clause) AND
             : ((GPL-2.0-or-later WITH Linux-syscall-note) OR MIT) AND
             : BSD-2-Clause AND (BSD-2-Clause OR Apache-2.0) AND BSD-3-Clause
             : AND BSD-3-Clause-Clear AND GFDL-1.1-no-invariants-or-later AND
             : GPL-1.0-or-later AND (GPL-1.0-or-later OR BSD-3-Clause) AND
             : (GPL-1.0-or-later WITH Linux-syscall-note) AND GPL-2.0-only AND
             : (GPL-2.0-only OR Apache-2.0) AND (GPL-2.0-only OR BSD-2-Clause)
             : AND (GPL-2.0-only OR BSD-3-Clause) AND (GPL-2.0-only OR CDDL-1.0)
             : AND (GPL-2.0-only OR GFDL-1.1-no-invariants-or-later) AND
             : (GPL-2.0-only OR GFDL-1.2-no-invariants-only) AND (GPL-2.0-only
             : WITH Linux-syscall-note) AND GPL-2.0-or-later AND
             : (GPL-2.0-or-later OR BSD-2-Clause) AND (GPL-2.0-or-later OR
             : BSD-3-Clause) AND (GPL-2.0-or-later OR CC-BY-4.0) AND
             : (GPL-2.0-or-later WITH GCC-exception-2.0) AND (GPL-2.0-or-later
             : WITH Linux-syscall-note) AND ISC AND LGPL-2.0-or-later AND
             : (LGPL-2.0-or-later OR BSD-2-Clause) AND (LGPL-2.0-or-later WITH
             : Linux-syscall-note) AND LGPL-2.1-only AND (LGPL-2.1-only OR
             : BSD-2-Clause) AND (LGPL-2.1-only WITH Linux-syscall-note) AND
             : LGPL-2.1-or-later AND (LGPL-2.1-or-later WITH Linux-syscall-note)
             : AND (Linux-OpenIB OR GPL-2.0-only) AND (Linux-OpenIB OR
             : GPL-2.0-only OR BSD-2-Clause) AND Linux-man-pages-copyleft AND
             : MIT AND (MIT OR Apache-2.0) AND (MIT OR GPL-2.0-only) AND (MIT OR
             : GPL-2.0-or-later) AND (MIT OR LGPL-2.1-only) AND (MPL-1.1 OR
             : GPL-2.0-only) AND (X11 OR GPL-2.0-only) AND (X11 OR
             : GPL-2.0-or-later) AND Zlib AND (copyleft-next-0.3.1 OR
             : GPL-2.0-or-later)
Description  : The kernel package contains the Linux kernel (vmlinuz), the core
             : of any Linux operating system.  The kernel handles the basic
             : functions of the operating system: memory allocation, process
             : allocation, device input and output, etc.

Name         : kernel-core
Version      : 6.9.6
Release      : 200.fc40
Architecture : x86_64
Size         : 69 M
Source       : kernel-6.9.6-200.fc40.src.rpm
Repository   : @System
From repo    : updates
Summary      : The Linux kernel
URL          : https://www.kernel.org/
License      : ((GPL-2.0-only WITH Linux-syscall-note) OR BSD-2-Clause) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR BSD-3-Clause) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR CDDL-1.0) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR Linux-OpenIB) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR MIT) AND
             : ((GPL-2.0-or-later WITH Linux-syscall-note) OR BSD-3-Clause) AND
             : ((GPL-2.0-or-later WITH Linux-syscall-note) OR MIT) AND
             : BSD-2-Clause AND (BSD-2-Clause OR Apache-2.0) AND BSD-3-Clause
             : AND BSD-3-Clause-Clear AND GFDL-1.1-no-invariants-or-later AND
             : GPL-1.0-or-later AND (GPL-1.0-or-later OR BSD-3-Clause) AND
             : (GPL-1.0-or-later WITH Linux-syscall-note) AND GPL-2.0-only AND
             : (GPL-2.0-only OR Apache-2.0) AND (GPL-2.0-only OR BSD-2-Clause)
             : AND (GPL-2.0-only OR BSD-3-Clause) AND (GPL-2.0-only OR CDDL-1.0)
             : AND (GPL-2.0-only OR GFDL-1.1-no-invariants-or-later) AND
             : (GPL-2.0-only OR GFDL-1.2-no-invariants-only) AND (GPL-2.0-only
             : WITH Linux-syscall-note) AND GPL-2.0-or-later AND
             : (GPL-2.0-or-later OR BSD-2-Clause) AND (GPL-2.0-or-later OR
             : BSD-3-Clause) AND (GPL-2.0-or-later OR CC-BY-4.0) AND
             : (GPL-2.0-or-later WITH GCC-exception-2.0) AND (GPL-2.0-or-later
             : WITH Linux-syscall-note) AND ISC AND LGPL-2.0-or-later AND
             : (LGPL-2.0-or-later OR BSD-2-Clause) AND (LGPL-2.0-or-later WITH
             : Linux-syscall-note) AND LGPL-2.1-only AND (LGPL-2.1-only OR
             : BSD-2-Clause) AND (LGPL-2.1-only WITH Linux-syscall-note) AND
             : LGPL-2.1-or-later AND (LGPL-2.1-or-later WITH Linux-syscall-note)
             : AND (Linux-OpenIB OR GPL-2.0-only) AND (Linux-OpenIB OR
             : GPL-2.0-only OR BSD-2-Clause) AND Linux-man-pages-copyleft AND
             : MIT AND (MIT OR Apache-2.0) AND (MIT OR GPL-2.0-only) AND (MIT OR
             : GPL-2.0-or-later) AND (MIT OR LGPL-2.1-only) AND (MPL-1.1 OR
             : GPL-2.0-only) AND (X11 OR GPL-2.0-only) AND (X11 OR
             : GPL-2.0-or-later) AND Zlib AND (copyleft-next-0.3.1 OR
             : GPL-2.0-or-later)
Description  : The kernel package contains the Linux kernel (vmlinuz), the core
             : of any Linux operating system.  The kernel handles the basic
             : functions of the operating system: memory allocation, process
             : allocation, device input and output, etc.

Name         : kernel-core
Version      : 6.9.7
Release      : 200.fc40
Architecture : x86_64
Size         : 69 M
Source       : kernel-6.9.7-200.fc40.src.rpm
Repository   : @System
From repo    : updates
Summary      : The Linux kernel
URL          : https://www.kernel.org/
License      : ((GPL-2.0-only WITH Linux-syscall-note) OR BSD-2-Clause) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR BSD-3-Clause) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR CDDL-1.0) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR Linux-OpenIB) AND
             : ((GPL-2.0-only WITH Linux-syscall-note) OR MIT) AND
             : ((GPL-2.0-or-later WITH Linux-syscall-note) OR BSD-3-Clause) AND
             : ((GPL-2.0-or-later WITH Linux-syscall-note) OR MIT) AND
             : BSD-2-Clause AND (BSD-2-Clause OR Apache-2.0) AND BSD-3-Clause
             : AND BSD-3-Clause-Clear AND GFDL-1.1-no-invariants-or-later AND
             : GPL-1.0-or-later AND (GPL-1.0-or-later OR BSD-3-Clause) AND
             : (GPL-1.0-or-later WITH Linux-syscall-note) AND GPL-2.0-only AND
             : (GPL-2.0-only OR Apache-2.0) AND (GPL-2.0-only OR BSD-2-Clause)
             : AND (GPL-2.0-only OR BSD-3-Clause) AND (GPL-2.0-only OR CDDL-1.0)
             : AND (GPL-2.0-only OR GFDL-1.1-no-invariants-or-later) AND
             : (GPL-2.0-only OR GFDL-1.2-no-invariants-only) AND (GPL-2.0-only
             : WITH Linux-syscall-note) AND GPL-2.0-or-later AND
             : (GPL-2.0-or-later OR BSD-2-Clause) AND (GPL-2.0-or-later OR
             : BSD-3-Clause) AND (GPL-2.0-or-later OR CC-BY-4.0) AND
             : (GPL-2.0-or-later WITH GCC-exception-2.0) AND (GPL-2.0-or-later
             : WITH Linux-syscall-note) AND ISC AND LGPL-2.0-or-later AND
             : (LGPL-2.0-or-later OR BSD-2-Clause) AND (LGPL-2.0-or-later WITH
             : Linux-syscall-note) AND LGPL-2.1-only AND (LGPL-2.1-only OR
             : BSD-2-Clause) AND (LGPL-2.1-only WITH Linux-syscall-note) AND
             : LGPL-2.1-or-later AND (LGPL-2.1-or-later WITH Linux-syscall-note)
             : AND (Linux-OpenIB OR GPL-2.0-only) AND (Linux-OpenIB OR
             : GPL-2.0-only OR BSD-2-Clause) AND Linux-man-pages-copyleft AND
             : MIT AND (MIT OR Apache-2.0) AND (MIT OR GPL-2.0-only) AND (MIT OR
             : GPL-2.0-or-later) AND (MIT OR LGPL-2.1-only) AND (MPL-1.1 OR
             : GPL-2.0-only) AND (X11 OR GPL-2.0-only) AND (X11 OR
             : GPL-2.0-or-later) AND Zlib AND (copyleft-next-0.3.1 OR
             : GPL-2.0-or-later)
Description  : The kernel package contains the Linux kernel (vmlinuz), the core
             : of any Linux operating system.  The kernel handles the basic
             : functions of the operating system: memory allocation, process
             : allocation, device input and output, etc.

**Comment by MarjaE2** [comment]
find /boot/efi:

/boot/efi
find: ‘/boot/efi’: Permission denied

**Comment by MarjaE2** [comment]
ls /usr/lib/modules:

6.2.12-300.t2.fc38.x86_64  6.9.5-200.fc40.x86_64  6.9.7-200.fc40.x86_64
6.9.4-200.t2.fc40.x86_64   6.9.6-200.fc40.x86_64

**Comment by sharpenedblade** [comment]
Something is wrong with your system, the installed kernel files and the installed packages are different. That should not happen.

**Comment by sharpenedblade** [comment]
Run `sudo dnf install kernel-6.9.7-200.t2 kernel-core- 6.9.7-200.t2`

**Comment by MarjaE2** [comment]
Last metadata expiration check: 0:11:24 ago on Fri 05 Jul 2024 09:51:06 PM EDT.
No match for argument: kernel-6.9.7-200.t2
No match for argument: kernel-core-
No match for argument: 6.9.7-200.t2
Error: Unable to find a match: kernel-6.9.7-200.t2 kernel-core- 6.9.7-200.t2

in case that space was causing this:

Last metadata expiration check: 0:12:05 ago on Fri 05 Jul 2024 09:51:06 PM EDT.
No match for argument: kernel-6.9.7-200.t2
No match for argument: kernel-core-6.9.7-200.t2
Error: Unable to find a match: kernel-6.9.7-200.t2 kernel-core-6.9.7-200.t2

**Comment by sharpenedblade** [comment]
> in case that space was causing this:
Sorry that was a typo. It looks like your system cant find the t2 kernels. Remove and reinstall the copr repo

**Comment by MarjaE2** [comment]
Still no luck.

**Comment by MarjaE2** [comment]
Okay, the lastest update added a t2 version.

**Comment by MarjaE2** [comment]
Now I'm getting "sorry, something went wrong" in Software, with "multiple matches of t2linux-scripts;1.0.0-1.fc40;noarch;copr:copr.fedorainfracloud.org:sharpenedblade:t2linux"

sudo dnf repolist only lists the one. Not sure how to track down any others.

**Comment by MarjaE2** [comment]
sudo dnf update seems to work, though.

**Comment by sharpenedblade** [comment]
Il look into fixing the bug, but until then `dnf upgrade` will always fix it.
