### ISSUE TITLE
Wifi Stopped Working After Update

### ISSUE THREAD

**Issue by MarjaE2** [t2linux/fedora#41]
I'm no sure exactly which update, or how to find logs to narrow this down.

It detects wifi networks, but is unable to connect, and reports and authentication failure.

Other devices, and an ethernet wifi device, still connect.

**Comment by AdityaGarg8** [comment]
Wpa supplicant has broken Wi-Fi for Broadcom chips, of which Macs are a part of. So, downgrade Wpa supplicant to 2.10

**Comment by sharpenedblade** [comment]
Run `sudo dnf install wpa_supplicant-1:2.10-10.fc40`. Make sure you are not on the `6.9.11-201` kernel, if you are go to an older kernel in the grub menu.
